---
title: "run_analysis.R Codebook"
author: "k. ricklin"
date: "Sept. 18, 2015"
output:
  html_document:
    keep_md: yes
    toc: true
    toc_depth: 2
    theme: spacelab
---

##Background
In December, 2012 four scientists of the University of Genova's Smartlab Research Laboratory conducted a series of experiments designed to measure human movement via smartphone technology. Utilizing the smartphone's built-in accelerometer and gyroscope, the scientists were able to measure six activities within a group of 30 volunteers. These experiments culminated in a data set the scientists labeled "Human Activity Recognition Using Smartphones (HARUS) Data Set Version 1.0".

##Project Description
The purpose of this project is to utilize the original HARUS data set and documentation to create a new, smaller data set of mean and standard deviation measurements of each activity. Each variable in the new data set will be labeled with descriptive activity names. Using this new data set as input, create a second, independent tidy data set containing the average of each variable for each activity and each subject.

##Data Processing

###Raw Data Collection
An overview of the HARUS Smartlab data set documentation was downloaded from:

http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones

The actual data set and descriptive files was downloaded from:

https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip

###Notes on Original HARUS Data Set 
The HARUS data set is made up of a number of text files. These files contain subject  activity measurements (up to 6 for each subject), subject identifiers, features, and activity lables. As subjects were randomly assigned to either a "TESTING" or "TRAINING" group, there are subject data files for each group. 

The "TRAINING" subject data is contained in:

- 'X_train.txt': Activity measurments for the "TRAINING" subjects.

- 'y_train.txt': "TRAINING" subject identifiers.

The "TESTING" subject data is contained in:

- 'X_test.txt': Activity measurments for the "TESTING" subjects.

- 'y_test.txt': "TESTING" subject ID.

For the six activities hundreds of "features" were measured:

- 'features.txt': Lists 561 features.

- 'features_info.txt': Shows information about the variables used on the feature vector.

- 'activity_labels.txt': List of the activities measured for each subject.

*Note: The HUARS data set includes "Inertial" files for both the "TESTING" and "TRAINING" groups that are NOT utilized as the data therin does not apply to this project.*

##Steps to Execute run_analysis.R

###Installation

*Note: "R" and/or "RStudio" must be installed on the target workstation.*

To create a tidy data file from the original HARUS data set:

1.  Fork the "kricklin/analysis"" repo to a new folder on your workstation
2.  Launch the "RStudio" application, or "R" from the command line
3.  Set the "working directory" to the new folder that contains the repo
3.  Run the "run_analysis.R" file.

###Code Processing Overview
The code in "analysis.R" performs the following steps:

####Part I - Set Up
1. Load required R packages
2. Download and expand the "Dataset.zip"" archive into a "./data" sub-directory

####Part II - Process Test Data - 2947 Rows
1) Load the Test Measurements into a data frame
2) Load the Test Subject IDs into a separate data frame
3) Add the Subject IDs to the Test Measurements in a new column
4) Load the Test Activities into a separate vector
5) Add the Activities to the Test Measurements in a new column

####Part III - Process Training Data - 7352 Rows
"Process Test Data" steps 1-5 are repeated for Training Data 

####Part IV - Merge Subject Data
1) Merge the mutated Test and Training Data Frames
2) Move "subject_id" and "activity" columns to first two columns
3) Using the "features.txt" file assign Column Names
4) Using the "activity_labels.txt" file to change the activity column values from numeric values (1-6) to text factors

The merged data results in a data frame of 10,299 Rows x 563 Columns

####Part V - Subset and Summarize
1) Subset all standard deviation and mean measurements 
2) Assign meaningful variable names to all features
3) Create a new, independent tidy data set with the average of each variable for each activity and each subject

At this point Data Processing is complete.

###Final Data Set Notes

####Dimensions
180 observations/rows of 82 variables/columns

####Data Summary
Each row represents all measurements for a single activity for a single subject.
Each column represents an average value for a specific measurement
 
####Variable Name Guide:
+ "f_" = "frequency"
+ "t_" = "time"
+ "_gyro" = "gyroscope"
+ "_accel" = "accelerometer"
+ "_std" = "standard deviation"

####Variable List:
 
 1. "subject_id"                    
 2. "partition" w/ 2 levels:
+  "TESTING"
+  "TRAINING"
 3. "activity" w/ 6 levels:
+  "WALKING"
+  "WALKING_UPSTAIRS"
+  "WALKING_DOWNSTAIRS"
+  "SITTING"
+  "STANDING"
+  "LAYING"
 4. "t_body_accel_mean_x"           
 5. "t_body_accel_mean_y"           
 6. "t_body_accel_mean_z"           
 7. "t_gravity_accel_mean_x"        
 8. "t_gravity_accel_mean_y"        
 9. "t_gravity_accel_mean_z"        
10. "t_body_accel_jerk_mean_x"      
11. "t_body_accel_jerk_mean_y"      
12. "t_body_accel_jerk_mean_z"      
13. "t_body_gyro_mean_x"            
14. "t_body_gyro_mean_y"            
15. "t_body_gyro_mean_z"            
16. "t_body_gyro_jerk_mean_x"       
17. "t_body_gyro_jerk_mean_y"       
18. "t_body_gyro_jerk_mean_z"       
19. "t_body_accel_mag_mean"         
20. "t_gravity_accel_mag_mean"      
21. "t_body_accel_jerk_mag_mean"    
22. "t_body_gyro_mag_mean"          
23. "t_body_gyro_jerk_mag_mean"     
24. "f_body_accel_mean_x"           
25. "f_body_accel_mean_y"           
26. "f_body_accel_mean_z"           
27. "f_body_accel_meanfreq_x"       
28. "f_body_accel_meanfreq_y"       
29. "f_body_accel_meanfreq_z"       
30. "f_body_accel_jerk_mean_x"      
31. "f_body_accel_jerk_mean_y"      
32. "f_body_accel_jerk_mean_z"      
33. "f_body_accel_jerk_meanfreq_x"  
34. "f_body_accel_jerk_meanfreq_y"  
35. "f_body_accel_jerk_meanfreq_z"  
36. "f_body_gyro_mean_x"            
37. "f_body_gyro_mean_y"            
38. "f_body_gyro_mean_z"            
39. "f_body_gyro_meanfreq_x"        
40. "f_body_gyro_meanfreq_y"        
41. "f_body_gyro_meanfreq_z"        
42. "f_body_accel_mag_mean"         
43. "f_body_accel_mag_meanfreq"     
44. "f_body_accel_jerk_mag_mean"    
45. "f_body_accel_jerk_mag_meanfreq"
46. "f_body_gyro_mag_mean"          
47. "f_body_gyro_mag_meanfreq"      
48. "f_body_gyro_jerk_mag_mean"     
49. "f_body_gyro_jerk_mag_meanfreq" 
50. "t_body_accel_std_x"            
51. "t_body_accel_std_y"            
52. "t_body_accel_std_z"            
53. "t_gravity_accel_std_x"         
54. "t_gravity_accel_std_y"         
55. "t_gravity_accel_std_z"         
56. "t_body_accel_jerk_std_x"       
57. "t_body_accel_jerk_std_y"       
58. "t_body_accel_jerk_std_z"       
59. "t_body_gyro_std_x"             
60. "t_body_gyro_std_y"             
61. "t_body_gyro_std_z"             
62. "t_body_gyro_jerk_std_x"        
63. "t_body_gyro_jerk_std_y"        
64. "t_body_gyro_jerk_std_z"        
65. "t_body_accel_mag_std"          
66. "t_gravity_accel_mag_std"       
67. "t_body_accel_jerk_mag_std"     
68. "t_body_gyro_mag_std"           
69. "t_body_gyro_jerk_mag_std"      
70. "f_body_accel_std_x"            
71. "f_body_accel_std_y"            
72. "f_body_accel_std_z"            
73. "f_body_accel_jerk_std_x"       
74. "f_body_accel_jerk_std_y"       
75. "f_body_accel_jerk_std_z"       
76. "f_body_gyro_std_x"             
77. "f_body_gyro_std_y"             
78. "f_body_gyro_std_z"             
79. "f_body_accel_mag_std"          
80. "f_body_accel_jerk_mag_std"     
81. "f_body_gyro_mag_std"           
82. "f_body_gyro_jerk_mag_std" 

###Columns NOT included:
 
The angle() variables listed below utilize mean signal values to calculate a value, and are NOT included in the final data set:

555. angle(tBodyAccMean,gravity)
556. angle(tBodyAccJerkMean),gravityMean)
557. angle(tBodyGyroMean,gravityMean)
558. angle(tBodyGyroJerkMean,gravityMean)
559. angle(X,gravityMean)
560. angle(Y,gravityMean)
561. angle(Z,gravityMean)

###Variable Notes
####"subject_id"
Integer - a value ranging from 1 - 30 that identifies each participant.

####"partition"
Factor - an identifier tying a subject to the "TRAINING" or "TESTING" group. 

####"activity"
Factor - identifies one of six activity measurments:
- "WALKING"
- "WALKING_UPSTAIRS"
- "WALKING_DOWNSTAIRS"
- "SITTING"
- "STANDING"
- "LAYING"

Some information on the variable including:
 - Class of the variable
 - Unique values/levels of the variable
 - Unit of measurement (if no unit of measurement list this as well)
 - In case names follow some schema, describe how entries were constructed (for example time-body-gyroscope-z has 4 levels of descriptors. Describe these 4 levels). 

(you can easily use Rcode for this, just load the dataset and provide the information directly form the tidy data file)

####Notes on variable 1:
If available, some additional notes on the variable not covered elsewehere. If no notes are present leave this section out.

##Original HUARS Data Set License
Use of this dataset in publications must be acknowledged by referencing the following publication [1] 

[1] Davide Anguita, Alessandro Ghio, Luca Oneto, Xavier Parra and Jorge L. Reyes-Ortiz. Human Activity Recognition on Smartphones using a Multiclass Hardware-Friendly Support Vector Machine. International Workshop of Ambient Assisted Living (IWAAL 2012). Vitoria-Gasteiz, Spain. Dec 2012

This dataset is distributed AS-IS and no responsibility implied or explicit can be addressed to the authors or their institutions for its use or misuse. Any commercial use is prohibited.

Jorge L. Reyes-Ortiz, Alessandro Ghio, Luca Oneto, Davide Anguita. November 2012.